experiment_name: Comp_01

study:
  T: 2
  M: 2
  
models:
  - vanilla
  - IG
  - AEI


BO:
  acqf_id: 0
  n_grid: 200

problem:
  k: 5
  n: 10
  x_min: 0.0
  x_max: 1.0
  n_min: 3
  n_max: 100
  test_function_index: 0
  noise_function_index: 0
  phi: 0.6
  tau: 0.7
  seed: 12345
  b0: 1
  b1: 0.5

plots:
  n_grid: 100
